apiVersion: v1
kind: Pod
metadata:
  name: minecraft-pod
  namespace: minecraft
spec:
  containers:
  - name: minecraft
    image: itzg/minecraft-server
    ports:
    - containerPort: 25565
    volumeMounts:
    - mountPath: /data
      name: minecraft-data
    env:
    - name: EULA
      value: "true"
    - name: VERSION
      value: "1.17.1"
  volumes:
  - name: minecraft-data
    persistentVolumeClaim:
      claimName: minecraft-volume-claim

