apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: minecraft
spec:
  selector:
    app: minecraft-app
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  externalIPs:
    - 172.16.2.1
    - 127.0.0.1
