apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-volume
  namespace: minecraft
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumePolicy: Retain
  storageClassName: minecraft-storage-class
  local:
    path: /srv/minecraft

