apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-volume-claim
  namespace: minecraft
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: minecraft-storage-class
  resources:
    requests:
      storage: 50Gi
