apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-app
  template:
    metadata:
      labels:
        app: minecraft-app
    spec:
      containers: []
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-volume-claim
