apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deployment
  namespace: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft-app
  template:
    metadata:
      labels:
        app: minecraft-app
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        ports: []
        volumeMounts:
        - mountPath: /data
          name: minecraft-data
        env:
        - name: EULA
          value: "true"
        - name: VERSION
          value: "1.17.1"
        - name: JVM_DD_OPTS
          value: "log4j2.formatMsgNoLookups:true"
        resources:
          limits:
            cpu: 4
            memory: 6Gi
          requests:
            cpu: 1
            memory: 500Mi
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-volume-claim
