apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-volume
  namespace: minecraft
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minecraft-storage-class
  local:
    path: /srv/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - centre.s6n.jp
